We use this log,reciprocal...... transformers to make columns normal(normal distribution).
If we make columns into normal distribution , we can handle skewness,outliers easily

In [29]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

from sklearn.preprocessing import FunctionTransformer
from sklearn.compose import ColumnTransformer

import scipy.stats as stats
import matplotlib.pyplot as plt
import seaborn as sns

In [30]:
df = pd.read_csv('Train.csv',usecols=['Survived','Age','Fare'])

In [31]:
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [34]:
df.isnull().sum()

Survived    0
Age         0
Fare        0
dtype: int64

In [33]:
df['Age'].fillna(df['Age'].mean(),inplace=True)

C:\Users\yango\AppData\Local\Temp\ipykernel_21088\694922604.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)

In [35]:
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [36]:
X = df.iloc[:,1:3]
y = df.iloc[:,0]

In [38]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)