In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_csv('orders.csv')
df2 = pd.read_csv('messages.csv')

In [3]:
df1.info() #date column's datatype should be datetime (to divide it further)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [4]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [6]:
df1.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [7]:
df2.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [8]:
#Converting into datetime datatype
df1['date'] = pd.to_datetime(df1['date'])

In [9]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [12]:
df1['date_year'] = df1['date'].dt.year                   #extracting year
df1['date_month'] = df1['date'].dt.month                 #extracting month
df1['date_month_name'] = df1['date'].dt.month_name()     #month name
df1['date_day'] = df1['date'].dt.day 
df1['date_dow'] = df1['date'].dt.dayofweek 
df1['date_dow_name'] = df1['date'].dt.day_name()

df1.drop(columns=['product_id','city_id','orders']).sample(5)

,date,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name
825,2019-03-25,2019,3,March,25,0,Monday
418,2019-07-16,2019,7,July,16,1,Tuesday
199,2019-01-27,2019,1,January,27,6,Sunday
117,2019-05-20,2019,5,May,20,0,Monday
778,2018-12-13,2018,12,December,13,3,Thursday

In [14]:
# is weekend ?
df1['date_is_weekend'] = np.where(df1['date_dow_name'].isin(['Sunday','Saturday']),1,0)
df1.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1

In [21]:
#extract quarter
df1['quarter'] = df1['date'].dt.quarter
df1.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_quarter,quarter
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,4,4
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,3,3
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,4,4
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,3,3
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1

In [24]:
#extract semester
df1['semester'] = np.where(df1['quarter'].isin([1,2]),1,2)
df1.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_quarter,quarter,semester
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,4,4,2
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,3,3,2
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,4,4,2
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,3,3,2
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1,1

In [34]:
#extract time between dates

import datetime
today = datetime.datetime.today()
today

datetime.datetime(2026, 6, 8, 12, 25, 14, 608374)

In [35]:
today - df1['date']

0     2372 days 12:25:14.608374
1     2854 days 12:25:14.608374
2     2785 days 12:25:14.608374
3     2487 days 12:25:14.608374
4     2710 days 12:25:14.608374
                 ...
995   2800 days 12:25:14.608374
996   2741 days 12:25:14.608374
997   2589 days 12:25:14.608374
998   2654 days 12:25:14.608374
999   2428 days 12:25:14.608374
Name: date, Length: 1000, dtype: timedelta64[ns]

In [36]:
(today-df1['date']).dt.days

0      2372
1      2854
2      2785
3      2487
4      2710
       ...
995    2800
996    2741
997    2589
998    2654
999    2428
Name: date, Length: 1000, dtype: int64

In [39]:
#weeks passed
np.round((today-df1['date'])/np.timedelta64(1,'W'),0)

0      339.0
1      408.0
2      398.0
3      355.0
4      387.0
       ...
995    400.0
996    392.0
997    370.0
998    379.0
999    347.0
Name: date, Length: 1000, dtype: float64

In [40]:
df2

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [41]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [42]:
df2['date'] = pd.to_datetime(df2['date'])

In [43]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [44]:
df2['hour'] = df2['date'].dt.hour
df2['min'] = df2['date'].dt.minute
df2['sec'] = df2['date'].dt.second
df2.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [45]:
#extract time part

df2['time'] = df2['date'].dt.time
df2.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [46]:
#time difference 
today - df2['date']

0     4558 days 11:35:14.608374
1     4422 days 12:45:14.608374
2     4908 days 12:04:14.608374
3     4210 days 11:54:14.608374
4     4607 days 13:14:14.608374
                 ...
995   5197 days 11:35:14.608374
996   4518 days 13:11:14.608374
997   4983 days 12:48:14.608374
998   5099 days 12:51:14.608374
999   4371 days 13:00:14.608374
Name: date, Length: 1000, dtype: timedelta64[ns]

In [47]:
#diff in sec
(today-df2['date'])/np.timedelta64(1,'s')

0      3.938529e+08
1      3.821067e+08
2      4.240947e+08
3      3.637869e+08
4      3.980925e+08
           ...
995    4.490625e+08
996    3.904027e+08
997    4.305773e+08
998    4.405999e+08
999    3.777012e+08
Name: date, Length: 1000, dtype: float64

In [48]:
#diff in min
(today-df2['date'])/np.timedelta64(1,'m')

0      6.564215e+06
1      6.368445e+06
2      7.068244e+06
3      6.063114e+06
4      6.634874e+06
           ...
995    7.484375e+06
996    6.506711e+06
997    7.176288e+06
998    7.343331e+06
999    6.295020e+06
Name: date, Length: 1000, dtype: float64

In [50]:
#diff in hours
np.round((today-df2['date'])/np.timedelta64(1,'h'),2)

0      109403.59
1      106140.75
2      117804.07
3      101051.90
4      110581.24
         ...
995    124739.59
996    108445.19
997    119604.80
998    122388.85
999    104917.00
Name: date, Length: 1000, dtype: float64